#ifndef LLVM_LIB_TARGET_RISCX_TARGETINFO_RISCXTARGETINFO_H
#define LLVM_LIB_TARGET_RISCX_TARGETINFO_RISCXTARGETINFO_H

namespace llvm {

class Target;

Target &getTheRISCXTarget();

} // namespace llvm

#endif // LLVM_LIB_TARGET_RISCX_TARGETINFO_RISCXTARGETINFO_H
