#ifndef LLVM_LIB_TARGET_RISCX_INSTPRINTER_RISCXINSTPRINTER_H
#define LLVM_LIB_TARGET_RISCX_INSTPRINTER_RISCXINSTPRINTER_H

#include "RISCXMCTargetDesc.h"
#include "llvm/MC/MCInstPrinter.h"

namespace llvm {

class TargetMachine;

class RISCXInstPrinter : public MCInstPrinter {
public:
  RISCXInstPrinter(const MCAsmInfo &MAI, const MCInstrInfo &MII,
                 const MCRegisterInfo &MRI)
      : MCInstPrinter(MAI, MII, MRI) {}

  // Autogenerated by tblgen.
  void printInstruction(const MCInst *MI, uint64_t Address, raw_ostream &O);
  static const char *getRegisterName(MCRegister Reg);
  void printMemOperand(const MCInst *MI, unsigned opNum, raw_ostream &O);
  void printPtrOperand(const MCInst *MI, unsigned opNum, raw_ostream &O);
  void printRegName(raw_ostream &OS, MCRegister Reg) const override;
  void printInst(const MCInst *MI, uint64_t Address, StringRef Annot,
                 const MCSubtargetInfo &STI, raw_ostream &O) override;

  bool printAliasInstr(const MCInst *MI, uint64_t Address, raw_ostream &OS);
  void printCustomAliasOperand(const MCInst *MI, uint64_t Address,
                               unsigned OpIdx, unsigned PrintMethodIdx,
                               raw_ostream &OS);

  std::pair<const char *, uint64_t> getMnemonic(const MCInst *MI) override;

private:
  void printOperand(const MCInst *MI, unsigned opNum, raw_ostream &O);
  void printImmediate(const MCInst *MI, unsigned opNum, raw_ostream &O);
};
} // end namespace llvm

#endif // LLVM_LIB_TARGET_RISCX_INSTPRINTER_RISCXINSTPRINTER_H
